version: '2.3'

services:

## Kibana service
  kibana:
    build: .
    container_name: kibana
    restart: always
#    depends_on:
#      elasticsearch:
#        condition: service_healthy
    ports:
     - "127.0.0.1:64296:5601"
    volumes:
     - /data/elk/certificates/:/usr/share/kibana/config/certificates:ro
    env_file:
     - /opt/tpot/etc/compose/es_serviceaccount_pw
    image: "podictive/kibana:debian"
